language: node_js
node_js:
    - stable
before_install:
    - openssl aes-256-cbc -K $encrypted_98a7d362e1e4_key -iv $encrypted_98a7d362e1e4_iv -in travis_deploy.enc -out travis_deploy -d
    - npm install -g gulp
    - chmod 600 travis_deploy
    - eval `ssh-agent -s`
    - ssh-add travis_deploy
install:
    - npm install
script:
    - npm run build
    - if [["$TRAVIS_BRANCH" = "master" || "$TRAVIS_BRANCH" = "development" ]]; then npm run deploy ; fi
